/* 本期快照的离线视觉与评测提示验收。输出截图到 screenshots/。 */
const fs=require('fs');
const path=require('path');
const {chromium}=require('playwright-core');
const file=path.resolve(__dirname,'../index.html');
const url='file:///'+encodeURI(file.replaceAll('\\','/'));
const shots=path.resolve(__dirname,'../screenshots');
fs.mkdirSync(shots,{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});
 const errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error'&&!/ERR_NETWORK_ACCESS_DENIED|fonts\.googleapis/.test(m.text()))errors.push(m.text())});
 await page.goto(url);await page.waitForTimeout(700);
 await page.screenshot({path:path.join(shots,'latest-overview-1440.png')});
 await page.click('a[href="#models"]');await page.waitForTimeout(300);
 const rankHelp=await page.locator('#rankMetric [data-rank="deepswe"] .metric-tip').textContent();
 for(const id of ['claude-sonnet55','claude-opus55','grok47'])await page.locator(`#modelTable [data-cmp="${id}"]`).click();
 await page.waitForTimeout(300);
 const tip=page.locator('#cmpBody .metric-help').filter({has:page.locator('.metric-tip b:text-is("DeepSWE v1.1（Agent）")')});
 await tip.hover();await page.waitForTimeout(150);
 const helpVisible=await page.locator('#metricTipPortal').isVisible();
 const helpText=await page.locator('#metricTipPortal').innerText();
 await page.screenshot({path:path.join(shots,'latest-compare-1440.png')});
 await tip.focus();const focusVisible=await page.locator('#metricTipPortal').isVisible();
 await page.setViewportSize({width:1280,height:900});await page.screenshot({path:path.join(shots,'latest-compare-1280.png')});
 await page.click('#trayClear');
 await page.setViewportSize({width:390,height:844});await page.click('a[href="#overview"]');await page.waitForTimeout(300);
 await page.screenshot({path:path.join(shots,'latest-overview-390.png')});
 const artifact=await browser.newPage();
 const artifactFile=path.resolve(__dirname,'../dist/artifact.html');
 await artifact.goto('file:///'+encodeURI(artifactFile.replaceAll('\\','/')));
 const artifactRows=await artifact.locator('#modelTable tbody tr').count();
 const artifactBroken=await artifact.locator('img').evaluateAll(images=>images.filter(i=>!i.complete||!i.naturalWidth).length);
 console.log(JSON.stringify({url,rankHelp,helpVisible,focusVisible,helpText,modelRows:await page.locator('#modelTable tbody tr').count(),compareModels:3,artifactRows,artifactBroken,errors},null,2));
 if(!helpVisible||!focusVisible||errors.length||artifactRows!==50||artifactBroken)process.exitCode=1;
 await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1});
